title = "KeebSupply Docs"
baseurl = "https://docs.keeb.supply/"
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en-US"
rssLimit = 10
summarylength = 20 # 70 (default)

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

copyRight = "Copyright (c) 2026 Burns & Kriener GbR"

[build.buildStats]
  enable = true

[outputs]
  home = ["html", "rss", "sitemap", "searchIndex", "llms"]
  page = ["html", "markdown"]
  404 = ["html"]
  section = ["html", "rss", "sitemap"]
  term = ["html", "rss", "sitemap"]

[outputFormats.searchIndex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true
  notAlternative = true

[outputFormats.markdown]
  baseName = "index"
  isHTML = false
  isPlainText = true
  mediaType = "text/markdown"

[outputFormats.llms]
  baseName = "llms"
  isHTML = false
  isPlainText = true
  mediaType = "text/plain"

# Add output format for section sitemap.xml
[outputFormats.sitemap]
  mediaType = "application/xml"
  baseName = "sitemap"
  isHTML = false
  isPlainText = true
  noUgly = true
  rel  = "sitemap"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[caches]
  [caches.getresource]
    dir = ":cacheDir/:project"
    maxAge = -1 # "30m"

[minify.tdewolff.html]
  keepComments = true # If set to false, build signatures are removed
  keepWhitespace = false

[pagination]
  pagerSize = 10

[imaging]
  anchor = "Center"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 85
  resampleFilter = "Lanczos"
