[[basics]]
  name = "Soldering"
  weight = 10
  identifier = "soldering"
  url = "/basics/soldering"

[[basics]]
  name = "Hardware"
  weight = 20
  identifier = "hardware"
  url = "/basics/hardware"

  [[basics]]
  name = "Firmware"
  weight = 30
  identifier = "firmware"
  url = "/basics/firmware"